### ISSUE TITLE
[BUG] Immutable -- Automatic screen lock does not lock

### ISSUE THREAD

**Issue by ghost** [Ultramarine-Linux/triage#22]
**Describe the bug**

If you enable the "Automatic Screen Lock" 

**To Reproduce**
1. Go to "Budgie Control Center"
2. Click on "Automatic screen lock" (to enable)
3. Set any time (30 seconds, for example)
4. Wait specified time (30 seconds, for example)

**Expected behavior**

For the screen to lock and require me to sign back to unlock.

**Screenshots**

n /a

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux Flagship Edition -- Immutable
 - Version

● ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
                   Digest: sha256:7d046049304d6e12b1ee1e198913dd9dff960005a5f2a37fdc5cd19a0e9c405d
                Timestamp: 2023-11-25T06:08:46Z

  ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
                   Digest: sha256:558022c52632c00fea243de55b5db0abc185319bd7d089de813ce6292e701b01
                Timestamp: 2023-11-25T06:08:46Z

**Additional context**

I do have the power save options disabled, including black screen. For example, power mode is set to performance, screen black is set to never, automatic suspend is set to off, and power button behavior is set to power off.  On the display settings, I once again, have black screen option disable. -- The only function I want to use is if I am away, that my screen will lock.

**Comment by nothingneko** [comment]
This sounds like a Budgie issue, I'll give it a test on mutable too and let you know :3
