### ISSUE TITLE
[BUG] Immutable -- Cannot switch between virtual desktops

### ISSUE THREAD

**Issue by ghost** [Ultramarine-Linux/triage#23]
**Describe the bug**

By the app menu, you have four (4) dots indicating four (4) virtual desktops. Clicking on this indicates you can even create more than four (4). However, you cannot drag items on your screen to another virtual desktop. Nor does clicking on any of the indicators change you over to another virtual desktop.  Lastly, there does not seem to be any "hot points' in any of the four (4) corners of the screen that would bring up the virtual desktops.

Note: Screenshot included

**To Reproduce**

1. Click on the indicators located by the app launcher menu (start menu).
2. Click on any of the dots
3. Attempt to drag any windows to the far left or right of the screen
4. Move your mouse to any of the four (4) corners of the screen

**Expected behavior**

Access to the other virtual desktop screens.

**Screenshots**

[Snapshot_2023-11-26_14-38-04](https://github.com/Ultramarine-Linux/ultramarine/assets/61557098/5cc76232-cc72-4a55-9aab-1f8a9f5d3221)

**Desktop (please complete the following information):**

 - OS: [e.g. Ultramarine Linux Flagship Edition -- Immutable
 - Version 
 - 
● ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
                   Digest: sha256:7d046049304d6e12b1ee1e198913dd9dff960005a5f2a37fdc5cd19a0e9c405d
                Timestamp: 2023-11-25T06:08:46Z

  ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
                   Digest: sha256:558022c52632c00fea243de55b5db0abc185319bd7d089de813ce6292e701b01

**Additional context**

N /  A

**Comment by Linux-Is-Best** [comment]
Small follow-up:  

Hot corners are disabled by default. There is a setting to enable it, but it doesn't work either. -- Sorry for not being clear on that fact (though I did touch base on that).
