### ISSUE TITLE
[BUG] Onboard crashed shortly after mouse hover

### ISSUE THREAD

**Issue by ghost** [Ultramarine-Linux/triage#25]
**Describe the bug**

Onboard (the on-screen keyboard app), exits shortly after hovering your mouse over the keyboard.  This makes it impossible to use.

**To Reproduce**
1. Go to the app menu launcher (start menu)
2. Click on "Onboard"
3. Move your mouse to hover over any of the keys
4. The app will exit on its own

**Expected behavior**

To be able to use the on-screen keyboard app (Onboard)

**Screenshots**

N / A

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux Flagship Edition -- Immutable
 - Version

● ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
                   Digest: sha256:2a7d1d3ddb36a05d584ba56ff1d0ecd4112541c1d09d24d00d517e2bcbf18054
                Timestamp: 2023-11-26T01:00:11Z

  ostree-unverified-image:docker://ghcr.io/ultramarine-linux/ultramarine-flagship:39
                   Digest: sha256:7d046049304d6e12b1ee1e198913dd9dff960005a5f2a37fdc5cd19a0e9c405d
                Timestamp: 2023-11-25T06:08:46Z

**Additional context**

I also do not recall having the option at the log-in screen.  This would be something you may wish to look into for users 1st loggin on with a yet to be configured Bluetooth keyboard.

**Comment by nothingneko** [comment]
I'll try this out on my hardware, are you on a tablet or using a mouse?

**Comment by Linux-Is-Best** [comment]
> I'll try this out on my hardware, are you on a tablet or using a mouse?

I am using a Workstation.  In fact, there is a full hardware probe for reference https://linux-hardware.org/?probe=ed0c7cdf91

(Note at the time of the problem, I had switched to testing to Universal Blue, but the hardware is the same)

**Comment by madonuko** [comment]
I can reproduce this on my non-immutable install. This seems to be an upstream issue:
```
15:07:00.679 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
15:07:00.829 WARNING Indicator: Failed to setup D-Bus match rule, no left-click Activate() for AppIndicator: org.freedesktop.DBus.Error.MatchRuleInvalid: Invalid match rule
zsh: segmentation fault (core dumped)  onboard
```

SegFault occurs when I tried to click anything on the virtual keyboard.

**Comment by Linux-Is-Best** [comment]
When running onboard from the terminal 

`
athens@ultramarine:/var/home/athens$ onboard
/usr/lib64/python3.12/site-packages/Onboard/utils.py:151: SyntaxWarning: invalid escape sequence '\d'
  """
/usr/lib64/python3.12/site-packages/Onboard/utils.py:220: SyntaxWarning: invalid escape sequence '\s'
  pattern = re.compile('>\n\s+([^<>\s].*?)\n\s+</', re.DOTALL)
/usr/lib64/python3.12/site-packages/Onboard/utils.py:221: SyntaxWarning: invalid escape sequence '\g'
  pretty_xml = pattern.sub('>\g<1></', ugly_xml)
/usr/lib64/python3.12/site-packages/Onboard/utils.py:356: SyntaxWarning: invalid escape sequence '\:'
  """
/usr/lib64/python3.12/site-packages/Onboard/utils.py:1542: SyntaxWarning: invalid escape sequence '\w'
  """(?:
/usr/lib64/python3.12/site-packages/Onboard/WordSuggestions.py:1253: SyntaxWarning: invalid escape sequence '\S'
  _section_begin_pattern = re.compile("\S*\s*$")
/usr/lib64/python3.12/site-packages/Onboard/WordSuggestions.py:1254: SyntaxWarning: invalid escape sequence '\S'
  _section_end_pattern = re.compile("\S*(?=\s*)")
/usr/lib64/python3.12/site-packages/Onboard/pypredict/lm_wrapper.py:302: SyntaxWarning: invalid escape sequence '\s'
  """ .*?
/usr/lib64/python3.12/site-packages/Onboard/pypredict/lm_wrapper.py:368: SyntaxWarning: invalid escape sequence '\s'
  tokenize_pattern = """
/usr/lib64/python3.12/site-packages/Onboard/pypredict/lm_wrapper.py:467: SyntaxWarning: invalid escape sequence '\w'
  if not re.match("""
/usr/lib64/python3.12/site-packages/Onboard/pypredict/lm_wrapper.py:504: SyntaxWarning: invalid escape sequence '\d'
  result = re.search("ngram (\d+)=\d+", line)
/usr/lib64/python3.12/site-packages/Onboard/pypredict/lm_wrapper.py:624: SyntaxWarning: invalid escape sequence '\w'
  target_word = re.search("^([\w]|[-'])*", prefix_to_end, re.UNICODE).group()
/usr/lib64/python3.12/site-packages/Onboard/TextDomain.py:144: SyntaxWarning: invalid escape sequence '\s'
  strings = re.split('(\s+)', context)
/usr/lib64/python3.12/site-packages/Onboard/TextDomain.py:161: SyntaxWarning: invalid escape sequence '\s'
  """
/usr/lib64/python3.12/site-packages/Onboard/TextDomain.py:291: SyntaxWarning: invalid escape sequence '\s'
  _growth_sections_pattern = re.compile("[^\s?#@]+", re.DOTALL)
/usr/lib64/python3.12/site-packages/Onboard/TextDomain.py:447: SyntaxWarning: invalid escape sequence '\['
  "^In \[[0-9]*\]: ",   # ipython
/usr/lib64/python3.12/site-packages/Onboard/TextDomain.py:450: SyntaxWarning: invalid escape sequence '\?'
  "^\?",                # vi reverse search
/usr/lib64/python3.12/site-packages/Onboard/TextDomain.py:451: SyntaxWarning: invalid escape sequence '\$'
  "\$ ",                # generic prompt
/usr/lib64/python3.12/site-packages/Onboard/TextDomain.py:459: SyntaxWarning: invalid escape sequence '\('
  "^\(.*\)`.*': ",  # bash incremental search
/usr/lib64/python3.12/site-packages/Onboard/TextDomain.py:739: SyntaxWarning: invalid escape sequence '\w'
  _url_pattern = re.compile("([\w-]+)|(\W+)", re.UNICODE)
/usr/lib64/python3.12/site-packages/Onboard/SpellChecker.py:324: SyntaxWarning: invalid escape sequence '\s'
  SPLITWORDS = re.compile("[^-_\s]+", re.UNICODE|re.DOTALL)
/usr/lib64/python3.12/site-packages/Onboard/LayoutLoaderSVG.py:98: SyntaxWarning: invalid escape sequence '\('
  self._layout_regex = re.compile("([^\(]+) (?: \( ([^\)]*) \) )?",
/usr/lib64/python3.12/site-packages/Onboard/LayoutLoaderSVG.py:447: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  raise Exceptions.LayoutFileError("Unrecognized modifier %s in" \
/usr/lib64/python3.12/site-packages/Onboard/Appearance.py:924: SyntaxWarning: invalid escape sequence '\w'
  _key_ids_pattern = re.compile('[\w-]+(?:[.][\w-]+)?', re.UNICODE)
/usr/lib64/python3.12/site-packages/Onboard/Appearance.py:1066: SyntaxWarning: invalid escape sequence '\w'
  key_ids = [x for x in re.findall('\w+(?:[.][\w-]+)?', text) if x]
12:02:54.366 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration disabled.
12:02:54.602 WARNING Indicator: Failed to setup D-Bus match rule, no left-click Activate() for AppIndicator: org.freedesktop.DBus.Error.MatchRuleInvalid: Invalid match rule
Segmentation fault (core dumped)

`
