### ISSUE TITLE
[BUG] `broadcom-wl` not preinstalled

### ISSUE THREAD

**Issue by embedvr** [Ultramarine-Linux/triage#55]
**Describe the bug**
Recently helped a friend install Ultramarine Linux 40 on a mid-2017 MacBook Air. On boot into the OS, there was no WiFi and we needed to install `broadcom-wl`. This should come preinstalled.

**To Reproduce**
1. Have mid-2017 MacBook Air
2. Install Ultramarine Linux 40
3. Log into OS
4. Have no WiFi.

**Expected behavior**
Have `broadcom-wl` preinstalled for machines that have a Broadcom based WiFi adapter.

**Screenshots**
dont have lol

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux Gnome Edition
 - Version 40

**Comment by nothingneko** [comment]
As far as I’m aware including broadcom-wl on systems without Broadcom WiFi may break WiFi, we include instructions for installing it on the wiki.

We’ll look into making it automatically installed by the new installer :3

**Comment by korewaChino** [comment]
You need an existing internet connection in the live environment for the installer to pick up and install broadcom-wl for you.

So you need some kind of existing connection already like Ethernet, USB tethering from a phone or from a mobile broadband modem to get the drivers to install sadly.

It wouldn't make much sense to include the akmod package files directly in the installation image at the moment.
