### ISSUE TITLE
[PACKAGE REQUEST] facetimehd

### ISSUE THREAD

**Issue by embedvr** [Ultramarine-Linux/triage#56]
## Which package(s) would you like to add?
- [facetimehd](https://github.com/patjak/facetimehd)

## Package information
- [x] Package is not already in the Ultramarine repositories
- [ ] If the package is already in the [Fedora repositories](https://packages.fedoraproject.org/), the package is a patched/forked version or an upstream version
- [x] Package is not deprecated or obsolete.
- [x] Package is not a private package or illegal to distribute (e.g a cracked copy or a package that is not publicly available for download)
- [x] Package is buildable and tested.

Name: facetimehd

Developer: [patjak](https://github.com/patjak)

License: GPL-2.0

Summary: Reverse engineered Linux driver for the FacetimeHD (Broadcom 1570) PCIe webcam

Description: Linux driver for the Facetime HD (Broadcom 1570) PCIe webcam found in recent Macbooks.

Website: https://github.com/patjak/facetimehd

## Maintainence

- [ ] Are you willing to maintain the package?
- [ ] If not, can you assign a willing maintainer?

### Maintainers
- Insert maintainers, you can also mention a GitHub username

**Comment by madonuko** [comment]
Ah, you're supposed to create a package request for this [here](https://github.com/terrapkg/packages/issues) instead because this is not specific to Ultramarine. I'll update this issue template to make this clear (it's pretty old).
